In [1]:
import pandas as pd
import numpy as np


In [2]:
train=pd.read_csv('train.csv')
train=train.drop(['Product_id','Customer_name','instock_date'],axis=1)

In [3]:
print(train.head())

   Stall_no  Market_Category Loyalty_customer Product_Category  Grade  Demand  \
0      37.0                2              Yes          Fashion      1      68   
1      38.0               24              Yes          Fashion      0      51   
2       9.0              447              Yes       Child_care      0      10   
3      50.0               23              Yes      Educational      2      48   
4       7.0               63              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0             0.0      376.0           11.0         2983.0         4713.0   
1             0.0      397.0           12.0         7495.0        10352.0   
2             0.0      250.0            9.0         5752.0         7309.0   
3             0.0      144.0           13.0         5090.0        20814.0   
4             1.0      211.0            4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.49

In [4]:
x=train.iloc[:,:-1].values
y=train.iloc[:,-1].values

In [5]:
y=np.array(y).reshape(len(y),1)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2,3])],remainder='passthrough')

In [7]:
x=ct.fit_transform(x)

In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')


In [9]:
x=imputer.fit_transform(x)

In [10]:
y=imputer.fit_transform(y)

In [11]:
print(x)

[[0.0000e+00 1.0000e+00 0.0000e+00 ... 1.1000e+01 2.9830e+03 4.7130e+03]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 1.2000e+01 7.4950e+03 1.0352e+04]
 [0.0000e+00 1.0000e+00 1.0000e+00 ... 9.0000e+00 5.7520e+03 7.3090e+03]
 ...
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 3.0000e+00 5.3030e+03 1.4614e+04]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 3.0000e+00 4.3340e+03 5.8490e+03]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 7.0000e+00 3.9750e+03 5.3830e+03]]


In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [13]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=4)
x=poly.fit_transform(x)

In [14]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [15]:
y_hat=reg.predict(x)

In [16]:
from sklearn.metrics import r2_score
print(r2_score(y,y_hat))

0.9825488643525386


# importin test data **set**

In [17]:
test=pd.read_csv('test.csv')



In [18]:
product_id=test[['Product_id']]

In [19]:
test=test.drop(['Product_id','Customer_name','instock_date'],axis=1)

In [20]:
x_test=np.array(test)


In [21]:
print(x)

[[ 1.00000000e+00 -7.98925185e-01  7.98925185e-01 ...  1.42158883e-02
   2.69860778e-02  5.12277796e-02]
 [ 1.00000000e+00 -7.98925185e-01  7.98925185e-01 ...  3.85898380e+00
   2.31000473e+00  1.38277903e+00]
 [ 1.00000000e+00 -7.98925185e-01  7.98925185e-01 ...  6.05689190e-02
   1.44713317e-02  3.45753967e-03]
 ...
 [ 1.00000000e+00  1.25168166e+00 -1.25168166e+00 ...  3.35929474e+00
   9.39096619e+00  2.62526074e+01]
 [ 1.00000000e+00 -7.98925185e-01  7.98925185e-01 ...  3.50779213e-03
  -1.54380407e-03  6.79439065e-04]
 [ 1.00000000e+00 -7.98925185e-01  7.98925185e-01 ...  3.46669347e-03
  -4.96461770e-03  7.10978031e-03]]


In [22]:
print(x_test)

[[39.0 205 'No ' ... 16.0 2576.0 3340]
 [49.0 3 'Yes' ... 16.0 1202.0 1955]
 [1.0 183 'No ' ... 9.0 7175.0 15715]
 ...
 [14.0 106 'Yes' ... 17.0 710.0 10894]
 [1.0 104 'Yes' ... 15.0 1477.0 5165]
 [3.0 165 'No ' ... 9.0 5538.0 7506]]


In [23]:
x_test=ct.fit_transform(x_test)

In [24]:
x_test=imputer.fit_transform(x_test)


In [25]:
x_test=sc.transform(x_test)

In [26]:
x_test=poly.fit_transform(x_test)

In [27]:
y_pred_test=reg.predict(x_test)

In [28]:
print(x.shape)

(6368, 12650)


In [29]:
print(x_test.shape)

(3430, 12650)


# to csv file

In [30]:
test_file=pd.DataFrame()

In [31]:
test_file['Product_id']=product_id

In [32]:
test_file['Selling_price']=y_pred_test

In [33]:
import pandas as pd
from google.colab import files

# Assuming y_pred_test is your DataFrame
test_file= pd.DataFrame(test_file)

# Save the DataFrame to a CSV file
csv_file_path = '/content/y_test_final.csv'
test_file.to_csv(csv_file_path, index=False)

# Download the CSV file
files.download(csv_file_path)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>